### ISSUE TITLE
Modify readme to say what this project is about

### ISSUE THREAD

**Issue by rsignell-usgs** [gdoney1701/COAWST-Test#4]
And explain that we are trying to create a nicer, python-based version of the [COAWST visualization web site](https://woodshole.er.usgs.gov/project-pages/cccp/public/COAWST.htm)

**Comment by rsignell-usgs** [comment]
And we might get @ocefpaf's input on how to approach this as well.     Thinking folium?

**Comment by rsignell-usgs** [comment]
Looking good...

**Comment by ocefpaf** [comment]
Not sure of `folium` is a good fit here. There is no direct support for those buttons.
IMO there is no scape writing some JS for something like that. I can take a look if `bokeh` is more advanced in that regard.
